version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "public"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/customer_table.sql:/docker-entrypoint-initdb.d/customer_table.sql